# -*- coding: utf-8 -*-
"""Folium_Map.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i1jsgzbfb56BF_Yyc7-vVtmSdhKdvloq
"""

import folium

My_Map=folium.Map([20.756,77.764],zoom_start=5)

My_Map

My_Map=folium.Map(location=[20.657,77.675],tiles='Stamen toner',zoom_start=5)

My_Map

